### PR TITLE
[ADD] Equipment-scrapping functionality enhanced

### PR DESCRIPTION
**Pull request by espo-tony**

### CODE REVIEW

**Comment by espo-tony** [comment]
@pedrobaeza can I ask you a review for this?

**Comment by pedrobaeza** [comment]
Yes, of course. Thanks for the PR. Let me check it later.

**Comment by pedrobaeza** [comment]
Thanks for the PR, Tony. It seems good, but I'm having the feeling that this feature deserves a totally separated module called _maintenance_equipment_scrap_ or similar, as it doesn't link with the account assets, and thus these 2 modules plus another one I have in mind to be put on a new repository OCA/maintenance. What do you think about that? If you agree, I start the procedure for requesting the repository and make initial PRs.

**Comment by espo-tony** [comment]
I agree. Indeed I think this functionality could find a better place in a separate module. I'll wait for you to create the new repo in order to propose it there.
Thank you.

**Comment by pedrobaeza** [comment]
The repository has been set: https://github.com/OCA/maintenance, so please make the PR there.

**Pull request closed without merging**
